shelf/urls.py
from django.conf.urls import patterns, include, url
from shelf.views import (AuthorListView,AuthorDetailView,BookListView,BookDetailView)

urlpatterns = patterns('',
    url(r'^autorzy/$',AuthorListView.as_view(),name='author-list'),
    url(r'^autorzy/(?P<pk>\d+)/$',AuthorDetailView.as_view(),name='author-detail'),
    url(r'^ksiazki/$',BookListView.as_view(),name='book-list'),
    url(r'^ksiazki/(?P<pk>\d+)/$',BookDetailView.as_view(),name='book-detail'),
)

shelf/models.py
#coding: utf-8
from __future__ import unicode_literals,absolute_import
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy

# Create your models here.

class Author(models.Model):
    first_name = models.CharField(verbose_name=_('first_name'),max_length=20)
    last_name = models.CharField(verbose_name=_('last_name'),max_length=50)

    def __str__(self):
        return '{first_name} {last_name}'.format(first_name=self.first_name,last_name=self.last_name)


    class Meta:
        ordering = ('last_name','first_name')
        verbose_name = _('author')
        verbose_name_plural = _('authors')



class Publisher(models.Model):
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name

class BookCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    categories = models.ManyToManyField(BookCategory)
    # author = models.ForeignKey(Author)


    def __str__(self):
        return self.title

    def get_absolute_url(self):   # drugi sposób wyswietlania - zobacz author_detail.html
        return reverse_lazy('shelf:book-detail',kwargs={'pk':self.id})

class BookEdition(models.Model):
    isbn = models.CharField(max_length=17,blank=True)
    publisher = models.ForeignKey(Publisher)
    book = models.ForeignKey(Book, related_name='editions')
    date = models.DateField()

    def __str__(self):
        return '{book.title},{publisher.name}'.format(book=self.book,publisher=self.publisher)




COVER_TYPES = (
    ('soft','soft'),
    ('hard','hard')
)

class BookItem(models.Model):
    edition = models.ForeignKey(BookEdition)
    catalogue_number = models.CharField(max_length=30)
    cover_type = models.CharField(max_length=4,choices=COVER_TYPES)

    def __str__(self):
        return '(edition),(cover)'.format(edition=self.edition,cover=self.cover_type_display())

shelf/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView,TemplateView
from django.http import HttpResponse

from .models import Author, Book


# Create your views here.

# pierwszy sposób:

# class MainPageView(View):
 #   def get(self, request, *args, **kwargs):
  #      return HttpResponse('ok')

# index_view = MainPageView.as_view() to przy drugim sposobie

class MainPageView(TemplateView):
    template_name = 'index.html'



class AuthorListView(ListView):
    model = Author


class AuthorDetailView(DetailView):
    model = Author


class BookListView(ListView):
    model = Book


class BookDetailView(DetailView):
    model = Book

shelf/templates/shelf/author_detail.html
{% extends "base.html" %}

{% block content %}

<div><a href="{% url 'shelf:author-list' %}">Powrot do listy autorow</a></div>
<a href="{% url 'shelf:book-list' %}">Porót do listy książek</a>

<ul>
<li><h3>profil autora:</h3> {{object.last_name}} {{object.first_name}}</li>
</ul>

<h2>Ksiazki</h2>
<ul>
{% for book in object.book_set.all %}
    <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
{% endfor %}
</ul>

{% endblock %}

shelf/templates/shelf/author_list.html
{% extends "base.html" %}

{% block content %}

<ul>
{% for author in object_list %}

    <li>informacja o autorze</li>
    <a href="{% url 'shelf:author-detail' author.id %}">{{author.first_name}} {{author.last_name}}</a>

{% endfor %}
</ul>
{% endblock %}

shelf/templates/shelf/book_detail.html
{% extends "base.html" %}{% load shelf_tags %}

{% block content %}

<div><a href="{% url 'shelf:author-list' %}">Powrot do listy autorow</a></div>
<a href="{% url 'shelf:book-list' %}">Porót do listy książek</a>

<h1>{{object.title}}</h1>

<h2>Wydania:</h2>

{% show_editions object %}

{% endblock %}

shelf/templates/shelf/book_list.html
{% extends "base.html" %}

{% block content %}
<ul>
{% for book in object_list %}
    <li><a href="{% url 'shelf:book-detail' book.id %}">{{ book.title }}</a> -
        {% for author in book.authors.all %}
            {{ author.first_name }} {{author.last_name }}
            {% if not forloop.last %},
            {% endif %}
        {% endfor %}
    </li>
{% endfor %}
</ul>

{% endblock %}

shelf/templates/tags/show_editions.html
{% load shelf_tags %}
<ul>{% for edition in editions %}
<li>{{ edition.date|pub_date }} - {{ edition.publisher.name }}</li>
{% endfor %}</ul>